require 'andrey.plugins.nvim-tree'
require 'andrey.plugins.treesitter'
require 'andrey.plugins.lualine'
require 'andrey.plugins.gitsigns'
require 'andrey.plugins.autopairs'
require 'andrey.plugins.lsp-zero'
require 'andrey.plugins.telescope'
